name: spred
channels:
  - pytorch
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anndata=0.9.1
  - anyio=3.5.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.7.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - chart-studio=1.1.0
  - click=8.0.4
  - cryptography=37.0.1
  - cudatoolkit=10.2.89
  - dbus=1.13.18
  - debugpy=1.5.1
  - entrypoints=0.4
  - expat=2.4.9
  - fa2=0.3.5
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.13.1
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - glpk=4.65
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.8.0
  - hdf5=1.12.2
  - hdf5plugin=4.1.1
  - icu=58.2
  - igraph=0.9.8
  - importlib-metadata=6.4.1
  - importlib_metadata=6.4.1
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipyparallel=8.4.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - leidenalg=0.8.10
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvmlite=0.38.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpfr=4.1.0
  - natsort=8.3.1
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.8.4
  - notebook=6.4.12
  - nspr=4.33
  - nss=3.74
  - numba=0.55.1
  - numexpr=2.8.4
  - numpy=1.21.6
  - openh264=2.1.1
  - openssl=1.1.1t
  - pandas=1.5.3
  - patsy=0.5.3
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.1.2
  - plotly=5.14.1
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pynndescent=0.5.8
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-fastjsonschema=2.15.1
  - python-igraph=0.9.10
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.1
  - qtwebkit=5.212
  - readline=8.1.2
  - regex=2022.7.9
  - requests=2.28.1
  - retrying=1.3.3
  - scanpy=1.9.3
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - session-info=1.0.0
  - setuptools=63.4.1
  - sip=6.6.2
  - sniffio=1.2.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - stdlib-list=0.8.0
  - suitesparse=5.10.1
  - tbb=2021.5.0
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.6.0
  - texttable=1.6.7
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - umap-learn=0.5.3
  - urllib3=1.26.11
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - widgetsnbextension=3.5.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - argon2-cffi==21.3.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - charset-normalizer==2.0.4
    - cycler==0.11.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==0.8.3
    - fastjsonschema==2.15.1
    - fonttools==4.25.0
    - idna==3.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jupyter-console==6.4.3
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - matplotlib-inline==0.1.2
    - munkres==1.1.4
    - nbclassic==0.3.5
    - nltk==3.7
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.20
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.11.2
    - pyopenssl==22.0.0
    - pyqt5-sip==12.11.0
    - python-dateutil==2.8.2
    - qtpy==2.0.1
    - send2trash==1.8.0
    - six==1.16.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - threadpoolctl==2.2.0
    - toml==0.10.2
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - wheel==0.37.1
